In [7]:
import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule
import numpy


a= numpy.random.rand(5,5)
a= a.astype(numpy.float32)

a_gpu=cuda.mem_alloc(a.nbytes)
cuda.memcpy_htod(a_gpu,a)

mod=SourceModule("""
    __global__ void doubles_matrix(float *a){
    int idx=threadIdx.x + threadIdx.y*4;
    a[idx]*=2;
    }
""")

func=mod.get_function("doubles_matrix")
func(a_gpu,block=(5,5,1))

a_doubled=numpy.empty_like(a)
cuda.memcpy_dtoh(a_doubled,a_gpu)

print("ORIGINAL MATRIX")
print(a)
print("Doubled matriz after pycuda execution")
print(a_doubled)


ORIGINAL MATRIX
[[0.61649674 0.6070714  0.33757612 0.19517626 0.95029074]
 [0.39599305 0.12357622 0.08617812 0.5249784  0.38273525]
 [0.8780678  0.9518983  0.44725764 0.3964146  0.00241983]
 [0.95738894 0.7487776  0.7369448  0.2001792  0.36650234]
 [0.0657244  0.6062149  0.85769314 0.9113781  0.963322  ]]
Doubled matriz after pycuda execution
[[1.2329935  1.2141428  0.67515224 0.39035252 1.9005815 ]
 [0.7919861  0.24715243 0.17235625 1.0499568  0.7654705 ]
 [1.7561356  1.9037966  0.8945153  0.7928292  0.00483965]
 [1.9147779  1.4975553  1.4738896  0.4003584  0.7330047 ]
 [0.13144879 0.6062149  0.85769314 0.9113781  0.963322  ]]


<ipython-input-7-8476c6b3802a>:13: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu

  mod=SourceModule("""


In [108]:
import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule
import numpy as np

n=10 

a=np.arange(1,n)
b=np.arange(n,n+10)
c=np.zeros(n)

a= a.astype(numpy.int)
b= b.astype(numpy.int)
c= c.astype(numpy.int)


a_gpu=cuda.mem_alloc(a.nbytes)
b_gpu=cuda.mem_alloc(b.nbytes)
c_gpu=cuda.mem_alloc(c.nbytes)



cuda.memcpy_htod(a_gpu,a)
cuda.memcpy_htod(b_gpu,b)
cuda.memcpy_htod(c_gpu,c)



mod=SourceModule("""
    __global__ void add(int* a, int* b, int* c){
    int tid = blockIdx.x;    
    if (tid < 10)
        c[tid] = a[tid] + b[tid];
}
""")

func=mod.get_function("add")
func(a_gpu,b_gpu,c_gpu,block=(n,1,1))



a_doubled=numpy.empty_like(a)
cuda.memcpy_dtoh(a_doubled,a_gpu)

b_doubled=numpy.empty_like(b)
cuda.memcpy_dtoh(b_doubled,b_gpu)

c_doubled=numpy.empty_like(c)
cuda.memcpy_dtoh(c_doubled,c_gpu)



print("A")
print(a_doubled)
print("B")
print(b_doubled)

print("REST°")
print(c_doubled)




A
[1 2 3 4 5 6 7 8 9]
B
[10 11 12 13 14 15 16 17 18 19]
REST°
[11  0  0  0  0  0  0  0  0  0]
